available_languages.push ({
	english_name: "English",
	native_name: "English",
	icon_file: "US.png",
	short_code: "en-US",
	active: true,

	translations: {

		APP_TITLE: 'BattleTech Tools',

		INDEX_WELCOME: 'Welcome',
		INDEX_H3_CORE: 'BattleTech Tools',

		WELCOME_BUTTON_MECH_CREATOR: '\'Mech Creator',
		WELCOME_BUTTON_MECH_CREATOR_DESC: 'Create a BattleMech',

		WELCOME_BUTTON_ALPHA_STRIKE: 'Alpha Strike',
		WELCOME_BUTTON_ALPHA_STRIKE_DESC: 'Alpha Strike Force Builder and In-Play App',

		WELCOME_H3_CORE: 'BattleTech Tools',
		WELCOME_H3_CREATORS_CORE: 'BattleTech Creators',

		WELCOME_H3_FORCE_BUILDERS_CORE: 'BattleTech Force Builders',

		GENERAL_SELECT_LANGUAGE: "Select Langage",
		GENERAL_SETTINGS: "Settings",
		GENERAL_CREDITS: 'Credits',
		GENERAL_COPYRIGHT: 'Copyright',
		GENERAL_WELCOME: 'Welcome',
		GENERAL_TECHNOLOGY: 'Technology',
		GENERAL_TECH: 'Tech',
		GENERAL_POINTS: 'Points',
		GENERAL_POINT: 'Point',
		GENERAL_POINT_VALUE: 'Point Value',
		GENERAL_RULES: 'Rules',
		GENERAL_BATTLETECH: 'BattleTech',
		GENERAL_MECH: '\'Mech',
		GENERAL_GROUP: 'Group',
		GENERAL_TON: 'Ton',
		GENERAL_TONS: 'Tons',
		GENERAL_CLAN: 'Clan',
		GENERAL_SKILL: 'Skill',
		GENERAL_SKILL_LEVEL: 'Skill Level',
		GENERAL_SKILL_PILOTING: 'Piloting Skill',
		GENERAL_SKILL_GUNNERY: 'Gunnery Skill',
		GENERAL_NAME: 'Name',
		GENERAL_CLANS: 'Clans',
		GENERAL_INNER_SPHERE: 'Inner Sphere',
		GENERAL_ALL: 'All',
		GENERAL_SEARCH: 'Search',
		GENERAL_SEARCH_RESULTS: 'Search Results',
		GENERAL_IMMOBILE: "Immobile",
		GENERAL_CANCEL: "Cancel",
		GENERAL_YES: "Yes",
		GENERAL_NO: "No",
		GENERAL_REAR: "rear",

		GENERAL_REMOVE: "Remove",
		GENERAL_SAVED: "Saved",

		GENERAL_SAVE_AS_NEW: "Save as New",
		GENERAL_SAVED_ITEM_AS: "Save Item As...",
		GENERAL_SAVE_NAME: "Save Name",
		GENERAL_SAVE: "Save",
		GENERAL_LOAD: "Load",
		GENERAL_SAVE_OVER_WARNING: "The existing item will be replaced.",
		GENERAL_LOAD_WARNING: "Warning: The loaded item will replace your current item. Please be sure that you have saved your current item.",
		GENERAL_NO_SAVED_ITEMS: "You have no saved items",
		GENERAL_LOAD_ITEM: "Load Saved Item",

		GENERAL_INTRODUCTORY: "Introductory",
		GENERAL_STANDARD: "Standard",
		GENERAL_ADVANCED: "Advanced",
		GENERAL_CLOSE: "Close",

		SETTINGS_IMPORT_EXPORT_SETTINGS: "Import/Export Data",
		SETTINGS_IMPORT_EXPORT_SETTINGS_DESC: "At some point I'm sure that you'll want to move or back up your hard work. Use this function to import and export your saved items.",
		SETTINGS_IMPORT: "Import",
		SETTINGS_IMPORT_DESC: "Browse to your backup JSON file on your local device. Warning: this will replace all your existing saved 'mechs and Alpha Strile saved groups.",
		SETTINGS_EXPORT: "Export",
		SETTINGS_EXPORT_DESC: "Click on the button below to download your saved 'mechs and favrorite alpha strike groups.",
		SETTINGS_CLICK_TO_DOWNLOAD: "Click to Download",
		SETTINGS_CLICK_TO_PREPARE: "Click to Prepare",

		AS_PLEASE_WAIT: "Please wait while information is retrieved from the master unit list.",
		AS_FAVORITE_GROUPS: "Favorite Groups",
		AS_ADD_TO_GROUP: "Add to Group",
		AS_GROUP_POINTS: "Group Points",
		AS_GROUP_NUM_UNITS: "Group # Units",
		AS_TOTAL_POINTS: "Total Points",
		AS_TOTAL_UNITS: "Total Units",
		AS_TOTAL_GROUPS: "Total Groups",
		AS_CURRENT_FORCE: "Current Force",
		AS_ADD_NEW_GROUP: "Add New Group",
		AS_GROUP_EMPTY: "This group is empty",
		AS_SEARCH_NO_MATCHES: "Sorry, there are no matches with those parameters",
		AS_PLAY_VIEW: "Play View",
		AS_CUSTOM_UNIT_NAME: "Custom Unit Name",
		AS_CUSTOM_GROUP_NAME: "Custom Star/Lance Name",
		AS_RESULTS_PROVIDED_BY_MUL: "Search results provided by the Master Unit List Website",
		AS_VIEWING_CARD: "Viewing Card",
		AS_ADD_TO_SELECTED_GROUP_NOTED_IN_DROPDOWN: "Add this unit to the group selected in the drop down in the top right of the search results",
		AS_UNIT_CUSTOMIZATION: "Unit Customization",
		AS_SELECT_DAMAGE_TAKEN: "Select Damage Taken",
		AS_ADD_TO_FAVORITES: "Add this force to your favorites",

		BM_MP_ABBR: "MP",

		BM_NEXT_STEP: "Next Step",
		BM_PREVIOUS_STEP: "Previous Step",
		BM_SUMMARY: "Summary",
		BM_BACK_TO_WELCOME: "Welcome",
		BM_EXPORTS: "Exporting and Printing",
		BM_BBCODE_TRO: "BBCode TRO",


		BUTTON_HOME_TITLE: "Home",
		BUTTON_HOME_DESC: "Back to the main screen",

		BM_INTRO_TITLE: "Welcome",
		BM_INTRO_DESC: "",
		BM_INTRO_TEXT: "<p>Welcome to a BattleTech 'mech builder.</p><p>This tool attempts to closely follow the steps in the <a href='http://bg.battletech.com/?wpsc-product=1095-2'>BattleTech TechManual</a> and the steps in that book should be referenced during 'mech creation</p>",
		BM_CLEAR_MECH: "Are you sure that you want to clear out your current 'mech?",
		BM_DELETE_ITEM: "Are you sure that you want to delete this item?",

		BM_TONS: "tons",
		BM_TON: "ton",
		BM_NO_ARMOR: "No Armor",

		BM_PRINTING_AND_PDF: "Printing and PDFs",

		BM_REMAINING_TONS: "Remaining Tons",
		BM_UNALLOCATED_ARMOR: "Unallocated Armor",
		BM_UNALLOCATED_CRITS: "Unallocated Criticals",
		BM_WEAPON_HEAT: "Weapon Heat",
		BM_MOVE_HEAT: "Move Heat",
		BM_HEAT_DISSIPATION: "Heat Dissipation",
		BM_HEAT_SUMMARY: "Heat Summary",
		BM_WELCOME_CLEAR_MECH: "Clear Current 'Mech",
		BM_WELCOME_LOAD_MECH: "Load 'Mech",
		BM_WELCOME_SAVE_MECH: "Save Current 'Mech",

		BM_STEP1_TITLE: "Step 1",
		BM_STEP1_DESC: "Design the Chassis",
		BM_STEP1_MECH_NAME: "Mech Model Name",
		BM_STEP1_MECH_TYPE: "Mech Type",
		BM_STEP1_MECH_ERA: "Mech Era",
		BM_STEP1_MECH_TONNAGE: "Mech Tonnage",
		BM_STEP1_MECH_TECH: "Mech Tech",
		BM_STEP1_SELECTED_STRICT: "Hide non-available weapons and equipment (will be gray otherwise)",

		BM_STEP2_TITLE: "Step 2",
		BM_STEP2_DESC: "Install engine and control systems",
		BM_STEP2_WALKING_MP: "Walking Movement Points",
		BM_STEP2_JUMPING_MP: "Jumping Movement Points",
		BM_STEP2_SELECT_JUMP: "Select Jumping MP",
		BM_STEP2_SELECT_WALK: "Select Walking MP",

		BM_STEP3_TITLE: "Step 3",
		BM_STEP3_DESC: "Add additional heat sinks",
		BM_STEP3_HS_TECH: "Heat Sink Technology",
		BM_STEP3_HS_ADD: "Add additional heat sinks",
		BM_STEP3_BM_INC_10_HS: "Your BattleMech includes 10 heat sinks.",
		BM_STEP3_BM_INC_10_DOUBLE_HS: "Your BattleMech includes 10 double heat sinks.",
		BM_STEP3_ADD_LABEL: "Additional heat sinks",
		BM_STEP3_CRITICAL_REQUIRED: "{hs_crits_required} critical slots are required for your engine class and selected heat sinks",
		BM_STEP3_CRITICAL_REQUIRED_NONE: "No additional critical slots are required for your engine class and selected heat sinks",
		BM_STEP3_CRITICAL_REQUIRED_SINGLE: "One critical slot is required for your engine class and selected heat sinks",
		BM_STEP3_SINGLE_HS: "Single Heat Sinks",
		BM_STEP3_DOUBLE_HS: "Double Heat Sinks",

		BM_STEP4_TITLE: "Step 4",
		BM_STEP4_DESC: "Add armor",
		BM_STEP4_ARMOR_WEIGHT: "Armor Weight",
		BM_STEP4_ARMOR_ALLOCATION: "Armor Allocation",
		BM_STEP4_MAX_ARMOR: "Maximum Armor",
		BM_STEP4_TOTAL_ARMOR: "Total Armor",
		BM_STEP4_UNALLOCATED_ARMOR: "Unallocated Armor",
		BM_STEP4_ALLOCATE_NONE: "Clear Armor",
		BM_STEP4_ALLOCATE_SANELY: "Allocate Sanely",
		BM_STEP4_ALLOCATE_MAX: "Allocate Max",

		BM_STEP5_TITLE: "Step 5",
		BM_STEP5_DESC: "Add weapons, ammunition and other equipment",
		BM_STEP5_ITEM_NAME: "Name",
		BM_STEP5_ITEM_CATEGORY: "Category",
		BM_STEP5_ITEM_SPACE: "Criticals",
		BM_STEP5_ITEM_WEIGHT: "Weight",
		BM_STEP5_ADD: "Add",
		BM_STEP5_ITEM_LOCATION: "Location",
		BM_STEP5_REMOVE: "Remove",
		BM_STEP5_INSTALLED_EQUIPMENT: "Installed Equipment",
		BM_STEP5_NO_EQUIPMENT_INSTALLED: "No equipment has been installed",
		BM_STEP5_SELECT_LOCATION: "Select Location",
		BM_STEP5_AVAILABLE_EQUIPMENT: "Available Equipment",
		BM_STEP5_ITEM_REAR: "Rear?",

		BM_STEP6_TITLE: "Step 6",
		BM_STEP6_DESC: "Complete the record sheet",
		BM_STEP6_UNALLOCATED_EQUIPMENT: "Unallocated Equipment",
		BM_STEP6_CRITICAL_TABLE: "Critical Table",
		BM_STEP6_RESET_ALLOCATIONS: "Reset Allocations",
		BM_STEP6_INSTRUCTIONS: "Instructions",
		BM_STEP6_INSTRUCTIONS_TEXT: "To assign equipment to your critical allocation table, just click on an assignable item then click on an unallocated location.",
		BM_STEP6_SELECT_AN_ITEM_TO_ALLOCATE: "Select an item to allocate",
		BM_STEP6_SELECT_AN_PLACE_TO_ALLOCATE: "Click on an available location",
		BM_STEP6_CANNOT_MOVE_THAT_ITEM: "You cannot move that item",
		BM_STEP6_CANNOT_BE_PLACED: "Item cannot be placed there",
		BM_STEP6_TORSO_AND_HEAD_ONLY: "Item may only be placed on torsos and head",
		BM_STEP6_TORSO_AND_LEGS_ONLY: "Item may only be placed on torsos and legs",

		BM_SUMMARY_TITLE: "Summary",
		BM_SUMMARY_DESC: "",
		BM_SUMMARY_TRO: "Technical Read Out",
		BM_SUMMARY_BV_CALC: "Battle Value Calculations",
		BM_SUMMARY_AS_CALC: "Alpha Strike Calculations",
		BM_SUMMARY_CBILL_CALC: "CBill Cost Calculations",

		BM_EXPORTS_TITLE: "Exports",
		BM_EXPORTS_DESC: "",
		BM_EXPORTS_OUTPUT: "Exporting and Printing",
		BM_EXPORTS_EXPORT_RECORD_SHEET: "Export Record Sheet",
		BM_EXPORTS_EXPORT_TRO: "Export TRO",
		BM_EXPORTS_EXPORT_FULL: "Export Both",

		BM_CRITS_LIFE_SUPPORT: "Life Support",
		BM_CRITS_HEAT_SINK: "Heat Sink",
		BM_CRITS_DOUBLE_HEAT_SINK: "Double Heat Sink",
		BM_CRITS_COCKPIT: "Cockpit",
		BM_CRITS_SENSORS: "Sensors",

		BM_CRITS_ACTUATOR_SHOULDER: "Shoulder",
		BM_CRITS_ACTUATOR_UPPER_ARM: "Upper Arm Actuator",
		BM_CRITS_ACTUATOR_LOWER_ARM: "Lower Arm Actuator",
		BM_CRITS_ACTUATOR_HAND: "Hand Actuator",
		BM_CRITS_ACTUATOR_HIP: "Hip",
		BM_CRITS_ACTUATOR_UPPER_LEG: "Upper Leg Actuator",
		BM_CRITS_ACTUATOR_LOWER_LEG: "Lower Leg Actuator",
		BM_CRITS_ACTUATOR_FOOT: "Foot Actuator",

		TRO_TYPE: "Type",

		TRO_TECHNOLOGY_BASE: "Technology Base",
		TRO_ERA: "Era",
		TRO_TONNAGE: "Tonnage",
		TRO_BATTLE_VALUE: "Battle Value",
		TRO_ALPHA_STRIKE_VALUE: "Alpha Strike Value",
		TRO_CBILL_COST: "C-Bill Cost",

		TRO_EQUIPMENT: "Equipment",
		TRO_MASS: "Mass",

		TRO_NOT_AVAILABLE: "n/a",

		TRO_INTERNAL_STRUCTURE: "Internal Structure",
		TRO_INTERNAL: "Internal",  // separate lines
		TRO_STRUCTURE: "Structure", // separate lines
		TRO_ENGINE: "Engine",
		TRO_WALKING: "Walking",
		TRO_RUNNING: "Running",
		TRO_JUMPING: "Jumping",
		TRO_HEAT_SINKS: "Heat Sinks",

		TRO_ARM_ACTUATORS: "Actuators",
		TRO_LOWER_LEFT: "LLA",
		TRO_LEFT_HAND: "LH",
		TRO_LOWER_RIGHT: "RLA",
		TRO_RIGHT_HAND: "RH",
		TRO_NO_LOWER_ARM_ACTUATORS: "No lower arm actuators",

		TRO_GYRO: "Gyro",
		TRO_COCKPIT: "Cockpit",
		TRO_JUMP_JETS: "Jump Jets",

		TRO_ARMOR_FACTOR: "Armor Factor",

		TRO_ARMOR_IS: "Internal Structure",
		TRO_ARMOR_VALUE: "Armor Value",
		TRO_ARMOR: "Armor", // split into 2 lines
		TRO_VALUE: "Value", // 2nd line

		TRO_ARMOR_HD: "Head",
		TRO_ARMOR_CT: "Center Torso",
		TRO_ARMOR_CTR: "Center Torso (Rear)",
		TRO_ARMOR_RLT: "R/L Torso",
		TRO_ARMOR_RLTR: "R/L Torso (Rear)",
		TRO_ARMOR_RT: "Right Torso",
		TRO_ARMOR_RTR: "Right Torso (Rear)",
		TRO_ARMOR_LT: "Left Torso",
		TRO_ARMOR_LTR: "Left Torso (Rear)",
		TRO_ARMOR_RLA: "R/L Arm",
		TRO_ARMOR_RA: "Right Arm",
		TRO_ARMOR_LA: "Left Arm",
		TRO_ARMOR_RLL: "R/L Leg",
		TRO_ARMOR_RL: "Right Leg",
		TRO_ARMOR_LL: "Left Leg",
		TRO_ARMOR_RLFL: "R/L Front Leg",
		TRO_ARMOR_RLRL: "R/L Rear Leg",
		TRO_ARMOR_RFL: "Right Front Leg",
		TRO_ARMOR_LFL: "Left Front Leg",
		TRO_ARMOR_RRL: "Right Rear Leg",
		TRO_ARMOR_LRL: "Left Rear Leg",

		TRO_WEAPONS_AND_AMMO: "Weapons<br />and Ammo",
		TRO_WEAPONS: "Weapons",
		TRO_AND_AMMO: "and Ammo",
		TRO_LOCATION: "Location",
		TRO_CRITICAL: "Critical",

		BUTTON_LANG_EN: 'English',
		BUTTON_LANG_DE: 'German',
		BUTTON_LANG_BR: 'Brazilian'
	}

} );
