// pub fn get_ability_list() -> [ASPilotAbility] {
//     [
//     ASPilotAbility {
//         id: 1,
//         ability: "Animal Mimicry".to_string(),
//         cost: 2,
//         summary: "Quadruped unit gains mobility bonus and ability to demoralize opponents".to_string(),
//     },
//     ASPilotAbility {
//         id: 2,
//         ability: "Antagonizer".to_string(),
//         cost: 3,
//         summary: "Unit can enrage an opponent for a brief period".to_string(),
//     },
//     ASPilotAbility {
//         id: 3,
//         ability: "Blood Stalker".to_string(),
//         cost: 2,
//         summary: "Unit may focus its attacks better on a preferred target until it is destroyed".to_string(),
//     },
//     ASPilotAbility {
//         id: 4,
//         ability: "Cluster Hitter".to_string(),
//         cost: 2,
//         summary: "Unit can deliver extra damage in an attack using missiles or flak weapons".to_string(),
//     },
//     ASPilotAbility {
//         id: 5,
//         ability: "Combat Intuition".to_string(),
//         cost: 3,
//         summary: "Unit may move and resolve fire before any other unit acts".to_string(),
//     },
//     ASPilotAbility {
//         id: 6,
//         ability: "Cross-Country".to_string(),
//         cost: 2,
//         summary: "Ground vehicle unit may enter some illegal terrain types, but at high Move cost".to_string(),
//     },
//     ASPilotAbility {
//         id: 7,
//         ability: "Demoralizer".to_string(),
//         cost: 3,
//         summary: "Unit can intimidate an opponent for a brief period".to_string(),
//     },
//     ASPilotAbility {
//         id: 8,
//         ability: "Dodge".to_string(),
//         cost: 2,
//         summary: "Unit can attempt to evade physical attacks".to_string(),
//     },
//     ASPilotAbility {
//         id: 9,
//         ability: "Dust-Off".to_string(),
//         cost: 2,
//         summary: "Enables airborne unit types to land or liftoff in non-clear terrain".to_string(),
//     },
//     ASPilotAbility {
//         id: 10,
//         ability: "Eagle's Eyes".to_string(),
//         cost: 2,
//         summary: "Unit gains (or augments) its ability to spot hidden units and avoid mines".to_string(),
//     },
//     ASPilotAbility {
//         id: 11,
//         ability: "Environmental Specialist".to_string(),
//         cost: 2,
//         summary: "Reduces movement and combat modifiers in a preferred environment".to_string(),
//     },
//     ASPilotAbility {
//         id: 12,
//         ability: "Fist Fire".to_string(),
//         cost: 2,
//         summary: "Unit delivers extra damage in physical attacks".to_string(),
//     },
//     ASPilotAbility {
//         id: 13,
//         ability: "Float Like a Butterfly".to_string(),
//         cost: 1,
//         summary: "Unit may force an opponent to reroll an attack with this unit as the target".to_string(),
//     },
//     ASPilotAbility {
//         id: 14,
//         ability: "Float Like a Butterfly".to_string(),
//         cost: 2,
//         summary: "Unit may force an opponent to reroll an attack with this unit as the target".to_string(),
//     },
//     ASPilotAbility {
//         id: 15,
//         ability: "Float Like a Butterfly".to_string(),
//         cost: 3,
//         summary: "Unit may force an opponent to reroll an attack with this unit as the target".to_string(),
//     },
//     ASPilotAbility {
//         id: 16,
//         ability: "Float Like a Butterfly".to_string(),
//         cost: 4,
//         summary: "Unit may force an opponent to reroll an attack with this unit as the target".to_string(),
//     },
//     ASPilotAbility {
//         id: 17,
//         ability: "Forward Observer".to_string(),
//         cost: 1,
//         summary: "Unit improves accuracy of indirect fire when used as a spotter".to_string(),
//     },
//     ASPilotAbility {
//         id: 18,
//         ability: "Golden Goose".to_string(),
//         cost: 3,
//         summary: "Improves accuracy for air-to-ground strafing, strike, and bombing attacks".to_string(),
//     },
//     ASPilotAbility {
//         id: 19,
//         ability: "Ground-Hugger".to_string(),
//         cost: 2,
//         summary: "Airborne unit may execute a double-strafe or double-strike air-to-ground attack".to_string(),
//     },
//     ASPilotAbility {
//         id: 20,
//         ability: "Headhunter".to_string(),
//         cost: 2,
//         summary: "Can automatically identify enemy command units".to_string(),
//     },
//     ASPilotAbility {
//         id: 21,
//         ability: "Heavy Lifter".to_string(),
//         cost: 1,
//         summary: "Enables increased carrying capacity with External Cargo rules".to_string(),
//     },
//     ASPilotAbility {
//         id: 22,
//         ability: "Hopper".to_string(),
//         cost: 1,
//         summary: "Unit may avoid being reduced below 1 inch of Move by MP Hits".to_string(),
//     },
//     ASPilotAbility {
//         id: 23,
//         ability: "Hot Dog".to_string(),
//         cost: 2,
//         summary: "Increases the Heat a unit can sustain before shutdown".to_string(),
//     },
//     ASPilotAbility {
//         id: 24,
//         ability: "Human TRO".to_string(),
//         cost: 1,
//         summary: "Unit can ignore the Concealing Unit Data rules vs. non-hidden opponents".to_string(),
//     },
//     ASPilotAbility {
//         id: 25,
//         ability: "Iron Will".to_string(),
//         cost: 1,
//         summary: "Unit can resist psychological attacks and receives a bonus during Morale checks".to_string(),
//     },
//     ASPilotAbility {
//         id: 26,
//         ability: "Jumping Jack".to_string(),
//         cost: 2,
//         summary: "Improves accuracy of any attack made when the unit uses jumping Move".to_string(),
//     },

//     ASPilotAbility {
//         id: 27,
//         ability: "Lucky".to_string(),
//         cost: 1,
//         summary: "Unit may reroll a limited number of failed attacks and Control Rolls per scenario".to_string(),
//     },
//     ASPilotAbility {
//         id: 28,
//         ability: "Lucky".to_string(),
//         cost: 2,
//         summary: "Unit may reroll a limited number of failed attacks and Control Rolls per scenario".to_string(),
//     },
//     ASPilotAbility {
//         id: 29,
//         ability: "Lucky".to_string(),
//         cost: 3,
//         summary: "Unit may reroll a limited number of failed attacks and Control Rolls per scenario".to_string(),
//     },
//     ASPilotAbility {
//         id: 30,
//         ability: "Lucky".to_string(),
//         cost: 4,
//         summary: "Unit may reroll a limited number of failed attacks and Control Rolls per scenario".to_string(),
//     },
//     ASPilotAbility {
//         id: 31,
//         ability: "Maneuvering Ace".to_string(),
//         cost: 2,
//         summary: "Reduces Move costs for woods/jungle terrain and aerospace atmospheric control".to_string(),
//     },
//     ASPilotAbility {
//         id: 32,
//         ability: "Marksman".to_string(),
//         cost: 2,
//         summary: "If unit attacks while stationary, may score extra critical after delivering 1 damage".to_string(),
//     },
//     ASPilotAbility {
//         id: 33,
//         ability: "Melee Master".to_string(),
//         cost: 2,
//         summary: "Unit increases its physical attack damage by half its Size (round up)".to_string(),
//     },
//     ASPilotAbility {
//         id: 34,
//         ability: "Melee Specialist".to_string(),
//         cost: 1,
//         summary: "Unit delivers physical attacks with greater accuracy".to_string(),
//     },
//     ASPilotAbility {
//         id: 35,
//         ability: "Multi-Tasker".to_string(),
//         cost: 2,
//         summary: "Unit can divide its weapon attack between two targets per turn".to_string(),
//     },
//     ASPilotAbility {
//         id: 36,
//         ability: "Natural Grace".to_string(),
//         cost: 3,
//         summary: "Unit gains 360-degree field of fire; reduces Move costs in ultra-heavy terrain".to_string(),
//     },
//     ASPilotAbility {
//         id: 37,
//         ability: "Oblique Artilleryman".to_string(),
//         cost: 1,
//         summary: "Improves accuracy and reduces scatter for all artillery weapon attacks".to_string(),
//     },
//     ASPilotAbility {
//         id: 38,
//         ability: "Oblique Attacker".to_string(),
//         cost: 1,
//         summary: "Improves accuracy for indirect fire, and enables indirect attacks without a spotter".to_string(),
//     },
//     ASPilotAbility {
//         id: 39,
//         ability: "Range Master".to_string(),
//         cost: 2,
//         summary: "Unit swaps normal range modifier for Medium, Long, or Extreme range with Short".to_string(),
//     },
//     ASPilotAbility {
//         id: 40,
//         ability: "Ride the Wash".to_string(),
//         cost: 4,
//         summary: "Unit reduces atmospheric combat modifiers; may execute special air-to-air attack".to_string(),
//     },
//     ASPilotAbility {
//         id: 41,
//         ability: "Sandblaster".to_string(),
//         cost: 2,
//         summary: "Unit improves accuracy and damage when only using AC and missile weapons".to_string(),
//     },
//     ASPilotAbility {
//         id: 42,
//         ability: "Shaky Stick".to_string(),
//         cost: 2,
//         summary: "Airborne unit is harder to hit from the ground during air-to-ground attacks".to_string(),
//     },
//     ASPilotAbility {
//         id: 43,
//         ability: "Sharpshooter".to_string(),
//         cost: 4,
//         summary: "If unit attacks while stationary, may score an extra critical after delivering full damage".to_string(),
//     },
//     ASPilotAbility {
//         id: 44,
//         ability: "Slugger".to_string(),
//         cost: 1,
//         summary: "'Mech unit can improvise its own melee weapons from suitable terrain".to_string(),
//     },
//     ASPilotAbility {
//         id: 45,
//         ability: "Sniper".to_string(),
//         cost: 3,
//         summary: "Unit reduces Medium, Long, and Extreme range modifiers by half.".to_string(),
//     },
//     ASPilotAbility {
//         id: 46,
//         ability: "Speed Demon".to_string(),
//         cost: 2,
//         summary: "Unit can move faster than normal".to_string(),
//     },
//     ASPilotAbility {
//         id: 47,
//         ability: "Stand-Aside".to_string(),
//         cost: 1,
//         summary: "Unit can pass directly through enemy units at extra Move cost".to_string(),
//     },
//     ASPilotAbility {
//         id: 48,
//         ability: "Street Fighter".to_string(),
//         cost: 2,
//         summary: "Unit may pre-empt an attack against it by enemies in base contact".to_string(),
//     },
//     ASPilotAbility {
//         id: 49,
//         ability: "Sure-Footed".to_string(),
//         cost: 2,
//         summary: "Unit receives bonus movement on paved or ice terrain and ignores skidding".to_string(),
//     },
//     ASPilotAbility {
//         id: 50,
//         ability: "Swordsman".to_string(),
//         cost: 2,
//         summary: "Unit can deliver improved damage or critical hits when using MEL special".to_string(),
//     },
//     ASPilotAbility {
//         id: 51,
//         ability: "Tactical Genius".to_string(),
//         cost: 3,
//         summary: "Enables command unit to reroll Initiatives once every 2 turns".to_string(),
//     },
//     ASPilotAbility{
//         id: 52,
//         ability: "(Drag Racer)".to_string(),
//         cost: 3,
//         summary: "Ground vehicle unit gains extra speed on ice or pavement; avoids skidding better".to_string(),
//     },
//     ASPilotAbility{
//         id: 53,
//         ability: "(Forest Ranger)".to_string(),
//         cost: 3,
//         summary: "Unit moves more easily through (and gains extra cover from) woods and jungle".to_string(),
//     },
//     ASPilotAbility{
//         id: 54,
//         ability: "(Frogman)".to_string(),
//         cost: 3,
//         summary: "Unit moves more easily than others while fully submerged".to_string(),
//     },
//     ASPilotAbility{
//         id: 55,
//         ability: "(Mountaineer)".to_string(),
//         cost: 3,
//         summary: "Unit moves more easily through level changes and rough terrain types".to_string(),
//     },
//     ASPilotAbility{
//         id: 56,
//         ability: "(Nightwalker)".to_string(),
//         cost: 3,
//         summary: "Unit ignores combat modifiers for darkness".to_string(),
//     },
//     ASPilotAbility{
//         id: 57,
//         ability: "(Sea Monster)".to_string(),
//         cost: 3,
//         summary: "Unit moves more easily and ignores attack penalties in water terrain".to_string(),
//     },
//     ASPilotAbility{
//         id: 58,
//         ability: "(Swamp Beast)".to_string(),
//         cost: 3,
//         summary: "Unit moves more easily through mud and swamp terrain; ignores bog down in same".to_string(),
//     },
//     ASPilotAbility{
//         id: 59,
//         ability: "Weapon Specialist".to_string(),
//         cost: 3,
//         summary: "Unit can deliver a more accurate attack as long as it uses only half its firepower".to_string(),
//     },
//     ASPilotAbility{
//         id: 60,
//         ability: "Wind Walker".to_string(),
//         cost: 2,
//         summary: "Unit ignores atmospheric combat modifiers and gains a bonus to landing and liftoff".to_string(),
//     },
//     ASPilotAbility{
//         id: 61,
//         ability: "Zweihander".to_string(),
//         cost: 2,
//         summary: "’Mech unit delivers more damage in physical attacks".to_string(),
//     },
//     ASPilotAbility{
//         id: 62,
//         ability: "Light Horseman".to_string(),
//         cost: 2,
//         summary: "Beast-mounted infantry unit moves faster, even through difficult terrain".to_string(),
//     },
//     ASPilotAbility{
//         id: 63,
//         ability: "Heavy Horse".to_string(),
//         cost: 2,
//         summary: "Beast-mounted infantry unit can inflict extra damage at point-blank range".to_string(),
//     },
//     ASPilotAbility{
//         id: 64,
//         ability: "Foot Cavalry".to_string(),
//         cost: 1,
//         summary: "Foot-based infantry unit moves faster, even through difficult terrain".to_string(),
//     },
//     ASPilotAbility{
//         id: 65,
//         ability: "Urban Guerrilla".to_string(),
//         cost: 3,
//         summary: "Infantry unit is harder to attack in urban terrain, and may “spawn” support".to_string(),
//     },
// ]
// }

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ASPilotAbility {
    id: u32,
    ability: String,
    cost: u32,
    summary: String,
}